title: "Asad's React Native Blog"  # Change this to your blog's title
email: "sadali3690@gmail.com"  # Your email address
description: >-
  Welcome to my blog where I share awesome content about React Native development, mobile app tips, and tutorials.
baseurl: ""  # Leave this empty if your site is at the root of the domain
url: "https://asadali2723.github.io"  # Your GitHub Pages URL
twitter_username: "your_twitter_handle"  # Optional: Replace with your Twitter handle
github_username: "asadali2723"  # Your GitHub username
# theme: "minimal-mistakes-jekyll"  # You are using the Minimal Mistakes theme

# Build settings
plugins:
  - jekyll-feed  # Plugin for RSS feed

# Exclude from processing (Uncomment if needed)
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
